### ISSUE TITLE
Migrating to Open API v3

### ISSUE THREAD

**Issue by ademdc** [iamfmjk/etsy#142]
In the launch stages page of the Etsy documentation it says that next year v2 will be removed.

https://developers.etsy.com/documentation/migration/index#launch-stages

Is there any plan to support v3 soon, because it will go obsolete if not?

**Comment by iamfmjk** [comment]
That's what I am going to work on. 
These days I am mainly "cleaning up the house" and within a week or two I hope to have a concrete plan for transition to the new Etsy API

**Comment by ademdc** [comment]
Great @iamfmjk. Thanks

**Comment by Divya-RS** [comment]
> That's what I am going to work on.
> These days I am mainly "cleaning up the house" and within a week or two I hope to have a concrete plan for transition to the new Etsy API

@iamfmjk any updates on this?
